name: sonar

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:


jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v8
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#make changes
